[package]
name = "crumble-impl-2"
version = "0.1.0"
authors = ["buckle2000 <buckle2000@zoho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fraction = "0.6.2"
nalgebra = "0.18"
partial-min-max = "0.3.0"
